# Mortality Study 01

## Setup
1. Manually enter a smaller subset of data for easy analysis
2. Remove spaces from column names
3. Load the full data set to be ready-to-go (or use as an alternative).
4. Load a small dataset with nulls (or errors)

In [352]:
import pandas as pd

### SMALL DATA SET:  Manually enter a smaller subset of data
#### DATA FRAME NAME: "mortality_data"

In [353]:
df_data=[[1900, '1-4 Years', 1983.8], 
         [1901, '1-4 Years', 1695.0],
         [1902, '1-4 Years', 1655.7],
         [1903, '1-4 Years', 1542.1],
         [1904, '1-4 Years', 1591.5],
         [1905, '1-4 Years', 1498.9],
         [1906, '1-4 Years', 1580.0],
         [1907, '1-4 Years', 1468.3],
         [1908, '1-4 Years', 1396.8],
         [1909, '1-4 Years', 1348.9],
         [1900, '5-9 Years', 466.1], 
         [1901, '5-9 Years', 427.6],
         [1902, '5-9 Years', 403.3],
         [1903, '5-9 Years', 414.7],
         [1904, '5-9 Years', 425.0],
         [1905, '5-9 Years', 396.3],
         [1906, '5-9 Years', 377.4],
         [1907, '5-9 Years', 365.6],
         [1908, '5-9 Years', 354.2],
         [1909, '5-9 Years', 330.2]]

df_columns=['Year', 'Age Group', 'Death Rate']

mortality_data = pd.DataFrame(data=df_data, columns=df_columns)

mortality_data

    Year  Age Group  Death Rate
0   1900  1-4 Years      1983.8
1   1901  1-4 Years      1695.0
2   1902  1-4 Years      1655.7
3   1903  1-4 Years      1542.1
4   1904  1-4 Years      1591.5
5   1905  1-4 Years      1498.9
6   1906  1-4 Years      1580.0
7   1907  1-4 Years      1468.3
8   1908  1-4 Years      1396.8
9   1909  1-4 Years      1348.9
10  1900  5-9 Years       466.1
11  1901  5-9 Years       427.6
12  1902  5-9 Years       403.3
13  1903  5-9 Years       414.7
14  1904  5-9 Years       425.0
15  1905  5-9 Years       396.3
16  1906  5-9 Years       377.4
17  1907  5-9 Years       365.6
18  1908  5-9 Years       354.2
19  1909  5-9 Years       330.2

### FULL DATA SET (Alternative):  look at the full dataset.
#### DATA FRAME NAME: "mort_full"
1. Load the csv and create a new data frame, called "mort_full"

In [354]:
mort_full = pd.read_csv("mortality.csv")
print()
print("Index: ", mort_full.index)
print("Columns: ", mort_full.columns)
print("Size: ", mort_full.size)
print("Shape: ", mort_full.shape)
print()
mort_full.head()
mort_full.tail()

Index:  RangeIndex(start=0, stop=476, step=1)
Columns:  Index(['Year', 'Age Group', 'Death Rate'], dtype='object')
Size:  1428
Shape:  (476, 3)

     Year    Age Group  Death Rate
471  2014  15-19 Years        45.5
472  2015  15-19 Years        48.3
473  2016  15-19 Years        51.2
474  2017  15-19 Years        51.5
475  2018  15-19 Years        49.2

### ALTERNATIVE DATA SET:  Includes null values
#### DATA FRAME NAME: "mort_data2"

In [355]:
df_data2=[[1900, '1-4 Years', 1983.8], 
         [1901, '1-4 Years', 1695.0],
         [1902, '1-4 Years', 1655.7],
         [1903, '1-4 Years', 1542.1],
         [1904, '1-4 Years', 1591.5],
         [1905, '1-4 Years', 1498.9],
         [1906, '1-4 Years', 1580.0],
         [1907, '1-4 Years', 1468.3],
         [1908, '1-4 Years', None],
         [1909, '1-4 Years', 1348.9],
         [1900, '5-9 Years', 466.1], 
         [1901, '5-9 Years', 427.6],
         [1902, '5-9 Years', 403.3],
         [1903, '5-9 Years', 414.7],
         [1904, '5-9 Years', 425.0],
         [1905, '5-9 Years', 396.3],
         [1906, '5-9 Years', 377.4],
         [1907, '5-9 Years', 365.6],
         [1908, '5-9 Years', 354.2],
         [1909, '5-9 Years', 330.2]]

df_columns2=['Year', 'Age Group', 'Death Rate']

mort_data2 = pd.DataFrame(data=df_data2, columns=df_columns2)

## Remove spaces from Column names for later

### Remove spaces from the Column Names for the small dataset  (But Camel Case)

In [356]:
mortality_data.columns = mortality_data.columns.str.replace(" ", "")

### Remove spaces from the Column Names for the full  dataset  (But Camel Case)

In [357]:
mort_full.columns = mort_full.columns.str.replace(" ", "")

## Examine the data

In [358]:
mort_data2.columns = mort_data2.columns.str.replace(" ", "")

In [359]:
mort_data2

    Year   AgeGroup  DeathRate
0   1900  1-4 Years     1983.8
1   1901  1-4 Years     1695.0
2   1902  1-4 Years     1655.7
3   1903  1-4 Years     1542.1
4   1904  1-4 Years     1591.5
5   1905  1-4 Years     1498.9
6   1906  1-4 Years     1580.0
7   1907  1-4 Years     1468.3
8   1908  1-4 Years        NaN
9   1909  1-4 Years     1348.9
10  1900  5-9 Years      466.1
11  1901  5-9 Years      427.6
12  1902  5-9 Years      403.3
13  1903  5-9 Years      414.7
14  1904  5-9 Years      425.0
15  1905  5-9 Years      396.3
16  1906  5-9 Years      377.4
17  1907  5-9 Years      365.6
18  1908  5-9 Years      354.2
19  1909  5-9 Years      330.2

### Get Meta values of the Dataframe

In [360]:
print("Index: ", mortality_data.index)
print("Columns: ", mortality_data.columns)
print("Size: ", mortality_data.size)
print("Shape: ", mortality_data.shape)

Index:  RangeIndex(start=0, stop=20, step=1)
Columns:  Index(['Year', 'AgeGroup', 'DeathRate'], dtype='object')
Size:  60
Shape:  (20, 3)

### describe() Method

In [361]:
mortality_data.describe()

              Year    DeathRate
count    20.000000    20.000000
mean   1904.500000   986.070000
std       2.946898   618.430172
min    1900.000000   330.200000
25%    1902.000000   401.550000
50%    1904.500000   907.500000
75%    1907.000000  1551.575000
max    1909.000000  1983.800000

In [362]:
mortality_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,20.0,1904.50,2.946898,1900.0,1902.00,1904.5,1907.000,1909.0
DeathRate,20.0,986.07,618.430172,330.2,401.55,907.5,1551.575,1983.8

### Accessing Columns

In [363]:
mortality_data

    Year   AgeGroup  DeathRate
0   1900  1-4 Years     1983.8
1   1901  1-4 Years     1695.0
2   1902  1-4 Years     1655.7
3   1903  1-4 Years     1542.1
4   1904  1-4 Years     1591.5
5   1905  1-4 Years     1498.9
6   1906  1-4 Years     1580.0
7   1907  1-4 Years     1468.3
8   1908  1-4 Years     1396.8
9   1909  1-4 Years     1348.9
10  1900  5-9 Years      466.1
11  1901  5-9 Years      427.6
12  1902  5-9 Years      403.3
13  1903  5-9 Years      414.7
14  1904  5-9 Years      425.0
15  1905  5-9 Years      396.3
16  1906  5-9 Years      377.4
17  1907  5-9 Years      365.6
18  1908  5-9 Years      354.2
19  1909  5-9 Years      330.2

In [364]:
mortality_data[['Year','DeathRate']].head(2)

   Year  DeathRate
0  1900     1983.8
1  1901     1695.0

When you use dot notation, the column names can’t contain any spaces. 
That’s why it’s a common practice to remove the spaces in column names as part of the cleaning phase.

In [365]:
mortality_data.DeathRate.head(2)

0    1983.8
1    1695.0
Name: DeathRate, dtype: float64

### Access Rows

In [366]:
mortality_data.query('Year == 1900')

    Year   AgeGroup  DeathRate
0   1900  1-4 Years     1983.8
10  1900  5-9 Years      466.1

### Accessing rows and columns

In [367]:
## Accessing one column and a subset of rows

In [368]:
mortality_data.query('Year == 1901').DeathRate

1     1695.0
11     427.6
Name: DeathRate, dtype: float64

In [369]:
mortality_data.query('Year == 1900')['DeathRate']

0     1983.8
10     466.1
Name: DeathRate, dtype: float64

### Using a list to get column data

In [370]:
mortality_data.query('Year == 1900')[['AgeGroup','DeathRate']]

     AgeGroup  DeathRate
0   1-4 Years     1983.8
10  5-9 Years      466.1

In [371]:
mortality_data.query('Year >= 1900 and Year <= 1905 and AgeGroup == "1-4 years"')[['Year', 'AgeGroup','DeathRate']]

Empty DataFrame
Columns: [Year, AgeGroup, DeathRate]
Index: []

### loc and iloc 

- use the loc[ ] (location) or iloc[ ] (integer location) accessor

- If you’ve used slices with your Python code, you know that a slice has a starting value, an ending value, and an optional step value with the values separated by colons.
- If you’re using positions instead of labels in your slices, those positions start from 0 and the ending position isn’t included in the result.
- So, for example, 1:3 is a slice that refers to the second and third values, but not the fourth.
- However, with the loc[] accessor, this works a little differently. When you use slices with DataFrames, the ending position is included.
- So, if you use 1:3 for a slice in the loc accessor, you get the rows where the index value is 1, 2, or 3.

### Loc
- You can select a range of rows, individual rows or "every x rows."

In [372]:
mortality_data.loc[0:1]

   Year   AgeGroup  DeathRate
0  1900  1-4 Years     1983.8
1  1901  1-4 Years     1695.0

In [373]:
mortality_data.loc[0:5:2]

   Year   AgeGroup  DeathRate
0  1900  1-4 Years     1983.8
2  1902  1-4 Years     1655.7
4  1904  1-4 Years     1591.5

### With column data

In [374]:
mortality_data.loc[[0,5,10],['AgeGroup','DeathRate']]

     AgeGroup  DeathRate
0   1-4 Years     1983.8
5   1-4 Years     1498.9
10  5-9 Years      466.1

### iloc

- With iloc the stop row and stop column are not inclusive, unlike the loc accessor
- The columns start at 0
- The index does not count but is displayed
- What happens when you reference a column that is not there?

In [375]:
mortality_data.iloc[4:7,[0,1,2]]

   Year   AgeGroup  DeathRate
4  1904  1-4 Years     1591.5
5  1905  1-4 Years     1498.9
6  1906  1-4 Years     1580.0

In [376]:
mortality_data.iloc[0:3,0:4]

   Year   AgeGroup  DeathRate
0  1900  1-4 Years     1983.8
1  1901  1-4 Years     1695.0
2  1902  1-4 Years     1655.7

### Exercise:   Use the code examples to experiment with different values.  Replace start and stop (change the cell to code)

#### Syntax for loc (Uses labels)
```
mortality_data.loc[<start>:[Col, Col, Col]
```
#### Syntax for iloc (Uses Index Numbers)

```
mortality_data.iloc[<start>:<stop>,<start>:<stop>]
```

## Working with the data
1. Sorting
2. Statistical Methods
3. Python for column arithmetic
4. Modifying string data in columns

### Sorting data using sort_values()

In [377]:
mortality_data.sort_values('DeathRate', ascending=False).head(3)

   Year   AgeGroup  DeathRate
0  1900  1-4 Years     1983.8
1  1901  1-4 Years     1695.0
2  1902  1-4 Years     1655.7

In [378]:
mortality_data.sort_values('DeathRate', ascending=True).head(3)

    Year   AgeGroup  DeathRate
19  1909  5-9 Years      330.2
18  1908  5-9 Years      354.2
17  1907  5-9 Years      365.6

### Challenge (Use Large Dataset):  
##### Problem: For each year, what age groups had the highest mortality rate.
- 
##### Solution: Sort by multiple columns in mixed orders. 
- Sort by the years with all of the years being grouped together, e.g. 1900, 1901, etc. 
- Within each group of years, sort by the Death Rate in descending order so that 
the largest number of deaths is at the top.

In [379]:
mort_full.sort_values(['Year','DeathRate'], ascending=[True,False]).head(12)

     Year     AgeGroup  DeathRate
0    1900    1-4 Years     1983.8
357  1900  15-19 Years      484.8
119  1900    5-9 Years      466.1
238  1900  10-14 Years      298.3
1    1901    1-4 Years     1695.0
358  1901  15-19 Years      454.4
120  1901    5-9 Years      427.6
239  1901  10-14 Years      273.6
2    1902    1-4 Years     1655.7
359  1902  15-19 Years      421.5
121  1902    5-9 Years      403.3
240  1902  10-14 Years      252.5

### Statistical Methods
-  Pandas provides one set of these methods for Series objects and another set with the same names for DataFrame objects.
- Apply them to columns that have data types that make sense for these methods. For example, the mean() method is designed to work with numerical data.

- count()
- mean()
- median()
- min()
- max()
- std()
- sum()
- quantile(q)


   |

#### Compare the mean death rate for the smaller dataset with the larger.  
- Does the mean improve over time and when older children are added to the dataset?

In [380]:
mortality_data.DeathRate.mean()

986.07

In [381]:
mort_full.DeathRate.mean()

192.92415966386554

### Count the values in all columns (does not include null)

In [382]:
mortality_data.count()

Year         20
AgeGroup     20
DeathRate    20
dtype: int64

### What if we apply this to a data frame with null values

In [383]:
mort_data2.count()

Year         20
AgeGroup     20
DeathRate    19
dtype: int64

In [384]:
mortality_data.DeathRate.sum()

19721.4

### Mean Centering
- The mean center is a way to make analysis of data more reasonable since it reduces the impact of outliers.
    - When doing a regression of salary based on years of experience, mean centering will reduce the 
      impact of salary at zero years of experience.
- All of the mean centered values in a set will add to zero.

##### When you have multiple variables, like grades based on study time and sleep time
You can use mean centering to see 
- What each variable does on its own
- What they do together

For example, 

- “If you study more than average, your score goes up.”
- “If you sleep more than average, your score goes up.”
- “If you do both, there’s a slight twist in how they combine.”

In [385]:
mortality_data.DeathRate.mean()

986.07

### Add a column for the Mean Centered values of Death Rate

In [387]:
mortality_data['MeanCentered'] = mortality_data.DeathRate - mortality_data.DeathRate.mean()

In [388]:
mortality_data

    Year   AgeGroup  DeathRate  MeanCentered
0   1900  1-4 Years     1983.8        997.73
1   1901  1-4 Years     1695.0        708.93
2   1902  1-4 Years     1655.7        669.63
3   1903  1-4 Years     1542.1        556.03
4   1904  1-4 Years     1591.5        605.43
5   1905  1-4 Years     1498.9        512.83
6   1906  1-4 Years     1580.0        593.93
7   1907  1-4 Years     1468.3        482.23
8   1908  1-4 Years     1396.8        410.73
9   1909  1-4 Years     1348.9        362.83
10  1900  5-9 Years      466.1       -519.97
11  1901  5-9 Years      427.6       -558.47
12  1902  5-9 Years      403.3       -582.77
13  1903  5-9 Years      414.7       -571.37
14  1904  5-9 Years      425.0       -561.07
15  1905  5-9 Years      396.3       -589.77
16  1906  5-9 Years      377.4       -608.67
17  1907  5-9 Years      365.6       -620.47
18  1908  5-9 Years      354.2       -631.87
19  1909  5-9 Years      330.2       -655.87

In [389]:
### Do they really add to zero?

In [390]:
mortality_data.MeanCentered.sum().round()

-0.0

### Add a column for death rate per thousand

In [391]:
mortality_data['PerThousand'] = mortality_data.DeathRate / 1000

In [392]:
mortality_data

    Year   AgeGroup  DeathRate  MeanCentered  PerThousand
0   1900  1-4 Years     1983.8        997.73       1.9838
1   1901  1-4 Years     1695.0        708.93       1.6950
2   1902  1-4 Years     1655.7        669.63       1.6557
3   1903  1-4 Years     1542.1        556.03       1.5421
4   1904  1-4 Years     1591.5        605.43       1.5915
5   1905  1-4 Years     1498.9        512.83       1.4989
6   1906  1-4 Years     1580.0        593.93       1.5800
7   1907  1-4 Years     1468.3        482.23       1.4683
8   1908  1-4 Years     1396.8        410.73       1.3968
9   1909  1-4 Years     1348.9        362.83       1.3489
10  1900  5-9 Years      466.1       -519.97       0.4661
11  1901  5-9 Years      427.6       -558.47       0.4276
12  1902  5-9 Years      403.3       -582.77       0.4033
13  1903  5-9 Years      414.7       -571.37       0.4147
14  1904  5-9 Years      425.0       -561.07       0.4250
15  1905  5-9 Years      396.3       -589.77       0.3963
16  1906  5-9 Years      377.4       -608.67       0.3774
17  1907  5-9 Years      365.6       -620.47       0.3656
18  1908  5-9 Years      354.2       -631.87       0.3542
19  1909  5-9 Years      330.2       -655.87       0.3302

## How to Shape the Data

### Indexes
- Default Index: DataFrames use a default index starting at 0; the last index is one less than the total number of rows.
- Custom Indexing: You can use set_index() to assign a column (or columns) as the index, which can aid operations like plotting.
- Non-Unique Index Check: Use verify_integrity=True in set_index() to ensure index values are unique; otherwise, an error is raised.
- Multi-Indexing: Setting the index with multiple columns (e.g., Year and AgeGroup) creates a multi-index, which allows for hierarchical indexing.
- Index Display: Index columns appear visually at a lower level than data columns in output displays.
- Limitations of Index Columns: Once a column becomes an index, it can’t be used as a parameter in methods unless reset.
- Resetting Index: Use reset_index() to convert index columns back to regular columns.
- inplace Parameter: Most methods, including set_index() and reset_index(), have an inplace option (default is False). It's best practice to leave it False.

In [393]:
mortality_data.head()

   Year   AgeGroup  DeathRate  MeanCentered  PerThousand
0  1900  1-4 Years     1983.8        997.73       1.9838
1  1901  1-4 Years     1695.0        708.93       1.6950
2  1902  1-4 Years     1655.7        669.63       1.6557
3  1903  1-4 Years     1542.1        556.03       1.5421
4  1904  1-4 Years     1591.5        605.43       1.5915

### Set the index to be the year
- The numerical index is no longer there.
- But we have multiple values for each year

### Set index to be the year

In [394]:
mortality_data = mortality_data.set_index('Year')
mortality_data

       AgeGroup  DeathRate  MeanCentered  PerThousand
Year
1900  1-4 Years     1983.8        997.73       1.9838
1901  1-4 Years     1695.0        708.93       1.6950
1902  1-4 Years     1655.7        669.63       1.6557
1903  1-4 Years     1542.1        556.03       1.5421
1904  1-4 Years     1591.5        605.43       1.5915
1905  1-4 Years     1498.9        512.83       1.4989
1906  1-4 Years     1580.0        593.93       1.5800
1907  1-4 Years     1468.3        482.23       1.4683
1908  1-4 Years     1396.8        410.73       1.3968
1909  1-4 Years     1348.9        362.83       1.3489
1900  5-9 Years      466.1       -519.97       0.4661
1901  5-9 Years      427.6       -558.47       0.4276
1902  5-9 Years      403.3       -582.77       0.4033
1903  5-9 Years      414.7       -571.37       0.4147
1904  5-9 Years      425.0       -561.07       0.4250
1905  5-9 Years      396.3       -589.77       0.3963
1906  5-9 Years      377.4       -608.67       0.3774
1907  5-9 Years      365.6       -620.47       0.3656
1908  5-9 Years      354.2       -631.87       0.3542
1909  5-9 Years      330.2       -655.87       0.3302

### Ensure that duplicate keys give an error

In [395]:
# mortality_data = mortality_data.set_index('Year',verify_integrity=True)
# mortality_data.head(2)

In [396]:
mortality_data = mortality_data.reset_index()

In [397]:
mortality_data

    Year   AgeGroup  DeathRate  MeanCentered  PerThousand
0   1900  1-4 Years     1983.8        997.73       1.9838
1   1901  1-4 Years     1695.0        708.93       1.6950
2   1902  1-4 Years     1655.7        669.63       1.6557
3   1903  1-4 Years     1542.1        556.03       1.5421
4   1904  1-4 Years     1591.5        605.43       1.5915
5   1905  1-4 Years     1498.9        512.83       1.4989
6   1906  1-4 Years     1580.0        593.93       1.5800
7   1907  1-4 Years     1468.3        482.23       1.4683
8   1908  1-4 Years     1396.8        410.73       1.3968
9   1909  1-4 Years     1348.9        362.83       1.3489
10  1900  5-9 Years      466.1       -519.97       0.4661
11  1901  5-9 Years      427.6       -558.47       0.4276
12  1902  5-9 Years      403.3       -582.77       0.4033
13  1903  5-9 Years      414.7       -571.37       0.4147
14  1904  5-9 Years      425.0       -561.07       0.4250
15  1905  5-9 Years      396.3       -589.77       0.3963
16  1906  5-9 Years      377.4       -608.67       0.3774
17  1907  5-9 Years      365.6       -620.47       0.3656
18  1908  5-9 Years      354.2       -631.87       0.3542
19  1909  5-9 Years      330.2       -655.87       0.3302

### Pivot the Data

##### Why Pivot Data in a DataFrame
Pivoting data in a DataFrame is useful when you want to **reshape** or **reorganize** the data to make it easier to analyze, visualize, or report. Here are key reasons:

##### Rearrange Data for Clarity
- **Convert rows into columns** (or vice versa) to make patterns or comparisons more visible.
- *Example*: Turn a column of years into column headers to see each year side by side.

##### Enable Better Analysis
- Summarize data in a more intuitive format, often used in time series or cross-tab analysis.
- *Example*: Show death rates by year (as columns) and age group (as rows).

##### Support for Plotting
- Many visualization tools work better when data is pivoted into a "wide format" where each column represents a distinct series.

##### Facilitate Calculations
- Pivoted data can make it easier to perform element-wise operations or aggregations across categories.

##### Tidy Data Principles
- Pivoting can help achieve a "tidy" format where:
  - Each variable forms a column.
  - Each observation forms a row.
  - Each type of observational unit forms a table.

#### Pivot Data for Mortality Data
- We need to think about what we want to pivot on, because we will drop the view of some data
from the view 
- Make mortality data wide pivoting on Death Rate
- Instead of having a multiple rows for each year, we now have all of the Death Rate data 
displayed in columns on a row for the year.  
- What did we lose?

In [398]:
mortality_wide = mortality_data.pivot(index='Year', columns='AgeGroup', values='DeathRate')
mortality_wide

AgeGroup  1-4 Years  5-9 Years
Year
1900         1983.8      466.1
1901         1695.0      427.6
1902         1655.7      403.3
1903         1542.1      414.7
1904         1591.5      425.0
1905         1498.9      396.3
1906         1580.0      377.4
1907         1468.3      365.6
1908         1396.8      354.2
1909         1348.9      330.2

In [399]:
mortality_wide2 = mort_full.pivot(index='Year', columns='AgeGroup', values='DeathRate')
mortality_wide2.head(10)

AgeGroup  1-4 Years  10-14 Years  15-19 Years  5-9 Years
Year
1900         1983.8        298.3        484.8      466.1
1901         1695.0        273.6        454.4      427.6
1902         1655.7        252.5        421.5      403.3
1903         1542.1        268.2        434.1      414.7
1904         1591.5        305.2        471.4      425.0
1905         1498.9        279.8        439.3      396.3
1906         1580.0        272.2        445.2      377.4
1907         1468.3        265.8        437.7      365.6
1908         1396.8        247.9        397.7      354.2
1909         1348.9        230.5        363.6      330.2

### Challenge:   The columns are not sorted numerically?

### Solution: Make all of the columns numeric by converting all single digit values to values with a leading zero. 
- The column labels in this example are string datatype. 
- When you clean the data for a DataFrame, you may need to modify the string data in a column. To do that, you can use Pandas methods or Python methods.
- Use the Pandas replace function with  a dictionary
- NOTE:  therer are several ways to do this

#### Small dataset

In [400]:
mortality_data.AgeGroup = mortality_data.AgeGroup.replace( {'1-4 Years':'01-04 Years','5-9 Years':'05-09 Years'})

#### Full dataset

In [401]:
mort_full.AgeGroup = mort_full.AgeGroup.replace( {'1-4 Years':'01-04 Years','5-9 Years':'05-09 Years'})

### Now try the pivot again

In [402]:
mortality_wide3 = mort_full.pivot(index='Year', columns='AgeGroup', values='DeathRate')
mortality_wide3.head(10)

AgeGroup  01-04 Years  05-09 Years  10-14 Years  15-19 Years
Year
1900           1983.8        466.1        298.3        484.8
1901           1695.0        427.6        273.6        454.4
1902           1655.7        403.3        252.5        421.5
1903           1542.1        414.7        268.2        434.1
1904           1591.5        425.0        305.2        471.4
1905           1498.9        396.3        279.8        439.3
1906           1580.0        377.4        272.2        445.2
1907           1468.3        365.6        265.8        437.7
1908           1396.8        354.2        247.9        397.7
1909           1348.9        330.2        230.5        363.6

### But you don't have to lose data 
- Let's do this to the small data set
- We do not specify the values specific values
- We are using the smaller data set since that one had the new columns added, not the full data set.

In [403]:
mortality_wide4 = mortality_data.pivot(index='Year', columns='AgeGroup')
mortality_wide4.head(10)

           DeathRate             MeanCentered             PerThousand  \
AgeGroup 01-04 Years 05-09 Years  01-04 Years 05-09 Years 01-04 Years
Year
1900          1983.8       466.1       997.73     -519.97      1.9838
1901          1695.0       427.6       708.93     -558.47      1.6950
1902          1655.7       403.3       669.63     -582.77      1.6557
1903          1542.1       414.7       556.03     -571.37      1.5421
1904          1591.5       425.0       605.43     -561.07      1.5915
1905          1498.9       396.3       512.83     -589.77      1.4989
1906          1580.0       377.4       593.93     -608.67      1.5800
1907          1468.3       365.6       482.23     -620.47      1.4683
1908          1396.8       354.2       410.73     -631.87      1.3968
1909          1348.9       330.2       362.83     -655.87      1.3489


AgeGroup 05-09 Years
Year
1900          0.4661
1901          0.4276
1902          0.4033
1903          0.4147
1904          0.4250
1905          0.3963
1906          0.3774
1907          0.3656
1908          0.3542
1909          0.3302